version: '3.8'

services:
  # backend:

  # frontend:

  mongodb:
    image: mongodb/mongodb-community-server
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongo.env
  
volumes:
  data: